spring:
    jpa:
        hibernate:
            ddl-auto:update
    datasource:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/healthcare
        driverClassName: com.mysql.jdbc.Driver
    server: 
        port: 8080
keycloak:
    realm: healthcare
    auth-server-url: http://localhost:8180/auth
    resource: springboot-keycloak
    public-client: true
    bearer-only: true
